//! Logs: a template plus a target rate, generated by one thread per running log.
//!
//! Every second the worker computes how many events (or bytes) are due,
//! generates them in batches and sleeps for the rest of the second. Rates below
//! one per second (`eps` per minute, hour or day) accumulate across seconds.

use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::time::{Duration, Instant};

use indexmap::IndexMap;
use parking_lot::{Mutex, RwLock};
use serde::{Deserialize, Serialize};

use crate::api_result::ApiResult;
use crate::maker::{MakerRef, MakerService, now_epoch_seconds};
use crate::sender::{SenderRef, SenderService};
use crate::storage::{Unloaded, entry_name, load_json, null_as_default, save_json};
use crate::template::LogTemplate;
use crate::worker::{STOP_TIMEOUT, StopSignal, Worker};

const BATCH_SIZE: usize = 1_000;
const SECOND: Duration = Duration::from_secs(1);

/// Body of log create/update/import requests and entries of `logs.json`.
#[derive(Debug, Clone, Default, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LogRequest {
    #[serde(default)]
    pub name: Option<String>,
    #[serde(default)]
    pub format: Option<String>,
    /// Target events (or bytes) per `eps_time_unit`.
    #[serde(default, deserialize_with = "null_as_default")]
    pub eps: i64,
    /// `events` (default) or `bytes`.
    #[serde(default)]
    pub eps_unit: Option<String>,
    /// `sec` (default), `min`, `hour` or `day`.
    #[serde(default)]
    pub eps_time_unit: Option<String>,
    #[serde(default, deserialize_with = "null_as_default")]
    pub sender: Vec<String>,
    #[serde(default, deserialize_with = "null_as_default")]
    pub paused: bool,
    #[serde(default)]
    pub reg_time: Option<i64>,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct LogDto {
    pub name: String,
    pub format: String,
    pub eps: i64,
    pub eps_unit: String,
    pub eps_time_unit: String,
    pub sender: Vec<String>,
    pub paused: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sample: Option<String>,
    pub current_eps: u64,
    pub count: u64,
    pub bytes: u64,
    pub bytes_per_sec: u64,
    pub reg_time: i64,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
struct LogSpec {
    name: String,
    format: String,
    eps: i64,
    eps_unit: String,
    eps_time_unit: String,
    sender: Vec<String>,
    reg_time: i64,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct StoredLog<'a> {
    #[serde(flatten)]
    spec: &'a LogSpec,
    paused: bool,
}

impl LogSpec {
    fn from_request(name: String, request: LogRequest, reg_time: i64) -> Self {
        Self {
            name,
            format: request.format.unwrap_or_default(),
            eps: request.eps,
            eps_unit: request.eps_unit.unwrap_or_else(|| "events".into()),
            eps_time_unit: request.eps_time_unit.unwrap_or_else(|| "sec".into()),
            sender: request.sender,
            reg_time,
        }
    }

    fn bytes_mode(&self) -> bool {
        self.eps_unit == "bytes"
    }

    fn divisor(&self) -> i64 {
        match self.eps_time_unit.as_str() {
            "min" => 60,
            "hour" => 3_600,
            "day" => 86_400,
            _ => 1,
        }
    }
}

/// A log definition with its template compiled and its makers and senders
/// acquired. Replaced as a whole when the log is updated.
pub struct LogConfig {
    spec: LogSpec,
    template: LogTemplate,
    /// Aligned with `template.names()`.
    makers: Vec<MakerRef>,
    senders: Vec<SenderRef>,
}

impl LogConfig {
    pub fn template(&self) -> &LogTemplate {
        &self.template
    }

    /// Generates a value from the maker of `template().names()[index]`.
    pub fn maker_value(&self, index: usize) -> String {
        self.makers[index].get_data()
    }

    fn render_event(&self) -> String {
        let values: Vec<String> = self.makers.iter().map(|m| m.get_data()).collect();
        self.template.render(&values)
    }
}

pub struct LogRuntime {
    config: RwLock<Arc<LogConfig>>,
    paused: AtomicBool,
    count: AtomicU64,
    bytes: AtomicU64,
    last_second_events: AtomicU64,
    last_second_bytes: AtomicU64,
    last_sample: Mutex<Option<String>>,
    /// Carry-over of fractional targets: (events, bytes).
    remainders: Mutex<(i64, i64)>,
    worker: Mutex<Option<Worker>>,
}

impl LogRuntime {
    fn new(config: LogConfig, paused: bool) -> Self {
        Self {
            paused: AtomicBool::new(paused),
            config: RwLock::new(Arc::new(config)),
            count: AtomicU64::new(0),
            bytes: AtomicU64::new(0),
            last_second_events: AtomicU64::new(0),
            last_second_bytes: AtomicU64::new(0),
            last_sample: Mutex::new(None),
            remainders: Mutex::new((0, 0)),
            worker: Mutex::new(None),
        }
    }

    pub fn config(&self) -> Arc<LogConfig> {
        Arc::clone(&self.config.read())
    }

    fn is_paused(&self) -> bool {
        self.paused.load(Ordering::SeqCst)
    }

    fn reset_metrics(&self) {
        self.count.store(0, Ordering::Relaxed);
        self.bytes.store(0, Ordering::Relaxed);
        self.last_second_events.store(0, Ordering::Relaxed);
        self.last_second_bytes.store(0, Ordering::Relaxed);
        *self.last_sample.lock() = None;
        *self.remainders.lock() = (0, 0);
    }

    fn dto(&self) -> LogDto {
        let config = self.config();
        let spec = &config.spec;
        LogDto {
            name: spec.name.clone(),
            format: spec.format.clone(),
            eps: spec.eps,
            eps_unit: spec.eps_unit.clone(),
            eps_time_unit: spec.eps_time_unit.clone(),
            sender: spec.sender.clone(),
            paused: self.is_paused(),
            sample: self.last_sample.lock().clone(),
            current_eps: self.last_second_events.load(Ordering::Relaxed),
            count: self.count.load(Ordering::Relaxed),
            bytes: self.bytes.load(Ordering::Relaxed),
            bytes_per_sec: self.last_second_bytes.load(Ordering::Relaxed),
            reg_time: spec.reg_time,
        }
    }

    /// Units due this second: `(remainder + raw) / divisor`, keeping the rest.
    fn next_target(&self, bytes_mode: bool, raw: i64, divisor: i64) -> u64 {
        if raw <= 0 || divisor <= 0 {
            return 0;
        }
        let mut remainders = self.remainders.lock();
        let remainder = if bytes_mode {
            &mut remainders.1
        } else {
            &mut remainders.0
        };
        let total = remainder.saturating_add(raw);
        *remainder = total % divisor;
        (total / divisor) as u64
    }

    fn run(&self, stop: &StopSignal) {
        while !stop.is_stopped() {
            let second = Instant::now();
            let (events, bytes) = self.generate_second(second, stop);
            self.last_second_events.store(events, Ordering::Relaxed);
            self.last_second_bytes.store(bytes, Ordering::Relaxed);
            if let Some(rest) = SECOND.checked_sub(second.elapsed()) {
                stop.sleep(rest);
            }
        }
        self.last_second_events.store(0, Ordering::Relaxed);
        self.last_second_bytes.store(0, Ordering::Relaxed);
    }

    /// Generates this second's target in batches, re-reading the configuration
    /// between batches so updates apply immediately.
    fn generate_second(&self, second: Instant, stop: &StopSignal) -> (u64, u64) {
        let config = self.config();
        if config.senders.is_empty() || self.is_paused() {
            return (0, 0);
        }
        let bytes_mode = config.spec.bytes_mode();
        let target = self.next_target(bytes_mode, config.spec.eps, config.spec.divisor());
        let below_target = |events: u64, bytes: u64| if bytes_mode { bytes < target } else { events < target };

        let (mut events, mut bytes) = (0, 0);
        while !stop.is_stopped() && below_target(events, bytes) && second.elapsed() < SECOND {
            let config = self.config();
            let mut sample = None;
            for _ in 0..BATCH_SIZE {
                if stop.is_stopped() || !below_target(events, bytes) {
                    break;
                }
                let data = config.render_event();
                for sender in &config.senders {
                    sender.deliver(&data);
                }
                let len = data.len() as u64;
                events += 1;
                bytes += len;
                self.count.fetch_add(1, Ordering::Relaxed);
                self.bytes.fetch_add(len, Ordering::Relaxed);
                sample = Some(data);
            }
            if sample.is_some() {
                *self.last_sample.lock() = sample;
            }
        }
        (events, bytes)
    }
}

pub struct LogService {
    makers: Arc<MakerService>,
    senders: Arc<SenderService>,
    path: PathBuf,
    logs: RwLock<IndexMap<String, Arc<LogRuntime>>>,
    unloaded: Unloaded,
    /// Serializes create/update/delete/start/stop.
    transition: Mutex<()>,
    persist_lock: Mutex<()>,
}

impl LogService {
    pub fn new(makers: Arc<MakerService>, senders: Arc<SenderService>, data_root: &Path) -> Self {
        Self {
            makers,
            senders,
            path: data_root.join("logs.json"),
            logs: RwLock::new(IndexMap::new()),
            unloaded: Unloaded::default(),
            transition: Mutex::new(()),
            persist_lock: Mutex::new(()),
        }
    }

    pub fn load(&self) -> std::io::Result<()> {
        let stored: Vec<serde_json::Value> = load_json(&self.path)?;
        for entry in stored {
            let result = match LogRequest::deserialize(&entry) {
                Ok(request) => self.register(request, true),
                Err(e) => ApiResult::error(e.to_string()),
            };
            if !result.is_success() {
                let reason = result.message.unwrap_or_default();
                tracing::warn!(
                    "cannot load stored log {}: {reason}; keeping it in storage",
                    entry_name(&entry)
                );
                self.unloaded.keep(entry);
            }
        }
        tracing::info!("loaded {} log(s), {} kept unloaded", self.count(), self.unloaded.len());
        Ok(())
    }

    fn snapshot(&self) -> Vec<Arc<LogRuntime>> {
        self.logs.read().values().cloned().collect()
    }

    /// All logs, newest first.
    pub fn list(&self) -> Vec<LogDto> {
        let mut logs: Vec<LogDto> = self.snapshot().iter().map(|log| log.dto()).collect();
        logs.sort_by(|a, b| b.reg_time.cmp(&a.reg_time));
        logs
    }

    pub fn count(&self) -> usize {
        self.logs.read().len()
    }

    pub fn get(&self, name: &str) -> Option<Arc<LogRuntime>> {
        self.logs.read().get(name).cloned()
    }

    fn validate(request: &LogRequest) -> Option<ApiResult> {
        if request.name.as_deref().unwrap_or_default().is_empty() {
            return Some(ApiResult::validation("name", "Name field value is required"));
        }
        if request.format.as_deref().unwrap_or_default().is_empty() {
            return Some(ApiResult::validation("format", "Format field value is required"));
        }
        None
    }

    pub fn create(&self, request: LogRequest) -> ApiResult {
        if let Some(error) = Self::validate(&request) {
            return error;
        }
        self.register(request, false)
    }

    pub fn import(&self, requests: Vec<LogRequest>) -> Vec<ApiResult> {
        requests.into_iter().map(|r| self.create(r)).collect()
    }

    pub fn import_file(&self, bytes: &[u8]) -> Vec<ApiResult> {
        match serde_json::from_slice::<Vec<LogRequest>>(bytes) {
            Ok(requests) => self.import(requests),
            Err(_) => vec![ApiResult::error("Log file import failed")],
        }
    }

    fn build_config(&self, spec: LogSpec) -> Result<LogConfig, String> {
        let template = LogTemplate::parse(&spec.format);
        let makers = self
            .makers
            .acquire_all(template.names())
            .map_err(|missing| format!("maker not found. [{}]", missing.join(", ")))?;
        let senders = self
            .senders
            .acquire_all(&spec.sender)
            .map_err(|missing| format!("sender not found. [{}]", missing.join(", ")))?;
        Ok(LogConfig {
            spec,
            template,
            makers,
            senders,
        })
    }

    fn register(&self, request: LogRequest, from_storage: bool) -> ApiResult {
        let _transition = self.transition.lock();
        let name = request.name.clone().unwrap_or_default();
        if self.logs.read().contains_key(&name) {
            return ApiResult::error(format!("{name} is the log name already in use"));
        }
        let reg_time = request.reg_time.filter(|t| *t > 0).unwrap_or_else(now_epoch_seconds);
        let paused = request.paused;
        let spec = LogSpec::from_request(name.clone(), request, reg_time);
        let format = spec.format.clone();
        let config = match self.build_config(spec) {
            Ok(config) => config,
            Err(reason) => return ApiResult::error(format!("Invalid log argument ({format}): {reason}")),
        };
        let runtime = Arc::new(LogRuntime::new(config, paused));
        if !runtime.is_paused() {
            if let Err(e) = start_worker(&name, &runtime) {
                tracing::error!("failed to start log thread {name}: {e}");
                return ApiResult::error("Log thread start failed");
            }
        }
        self.logs.write().insert(name.clone(), runtime);
        if !from_storage {
            self.unloaded.forget(&name);
            if let Err(result) = self.persist() {
                return result;
            }
        }
        ApiResult::success("Successful log registration")
    }

    /// Replaces the definition of a log (its paused state is kept) and resets
    /// its counters.
    pub fn update(&self, name: &str, mut request: LogRequest) -> ApiResult {
        request.name = Some(name.to_owned());
        if let Some(error) = Self::validate(&request) {
            return error;
        }
        let _transition = self.transition.lock();
        let Some(runtime) = self.get(name) else {
            return ApiResult::error("Update log failed");
        };
        let current = runtime.config();
        let spec = LogSpec::from_request(name.to_owned(), request, current.spec.reg_time);
        let config = match self.build_config(spec) {
            Ok(config) => config,
            Err(reason) => return ApiResult::error(format!("Update log failed ({reason})")),
        };
        *runtime.config.write() = Arc::new(config);
        runtime.reset_metrics();
        drop(current);
        match self.persist() {
            Ok(()) => ApiResult::success("Successfully updated log"),
            Err(result) => result,
        }
    }

    pub fn delete(&self, name: &str) -> ApiResult {
        let _transition = self.transition.lock();
        let Some(runtime) = self.logs.write().shift_remove(name) else {
            return ApiResult::error("Log does not exist");
        };
        stop_worker(name, &runtime);
        drop(runtime);
        match self.persist() {
            Ok(()) => ApiResult::success("Successfully deleted log"),
            Err(result) => result,
        }
    }

    /// Pauses (stops the thread) or resumes a log.
    pub fn set_paused(&self, name: &str, paused: bool) -> ApiResult {
        let _transition = self.transition.lock();
        let Some(runtime) = self.get(name) else {
            return ApiResult::error("Log does not exist");
        };
        let was_paused = runtime.paused.swap(paused, Ordering::SeqCst);
        if paused {
            stop_worker(name, &runtime);
        } else if was_paused {
            if let Err(e) = start_worker(name, &runtime) {
                runtime.paused.store(true, Ordering::SeqCst);
                tracing::error!("failed to resume log thread {name}: {e}");
                return ApiResult::error("Log thread start failed");
            }
        }
        match self.persist() {
            Ok(()) => ApiResult::success(if paused { "Log stopped" } else { "Log started" }),
            Err(result) => result,
        }
    }

    /// Renders `format` once with current maker values; unknown makers keep
    /// their `<name>` token.
    pub fn preview(&self, format: &str) -> ApiResult {
        let template = LogTemplate::parse(format);
        let values: Vec<Option<String>> = template
            .names()
            .iter()
            .map(|name| self.makers.peek(name).map(|maker| maker.get_data()))
            .collect();
        ApiResult::success(template.render_with(|i| values[i].as_deref())).with_notification(false)
    }

    pub fn shutdown(&self) {
        let _transition = self.transition.lock();
        let logs = std::mem::take(&mut *self.logs.write());
        for (name, runtime) in logs {
            stop_worker(&name, &runtime);
        }
    }

    fn persist(&self) -> Result<(), ApiResult> {
        let _guard = self.persist_lock.lock();
        let runtimes = self.snapshot();
        let configs: Vec<(Arc<LogConfig>, bool)> = runtimes.iter().map(|r| (r.config(), r.is_paused())).collect();
        let stored: Vec<StoredLog> = configs
            .iter()
            .map(|(config, paused)| StoredLog {
                spec: &config.spec,
                paused: *paused,
            })
            .collect();
        self.unloaded
            .merge(&stored)
            .and_then(|entries| save_json(&self.path, &entries))
            .map_err(|e| {
                tracing::error!("failed to save {}: {e}", self.path.display());
                ApiResult::error(format!("Failed to save log storage ({e})"))
            })
    }
}

fn start_worker(name: &str, runtime: &Arc<LogRuntime>) -> std::io::Result<()> {
    let mut worker = runtime.worker.lock();
    if worker.as_ref().is_some_and(|w| !w.is_finished()) {
        return Ok(());
    }
    let log = Arc::clone(runtime);
    *worker = Some(Worker::spawn(&format!("log-{name}"), move |stop| log.run(stop))?);
    tracing::info!("started log thread {name}");
    Ok(())
}

fn stop_worker(name: &str, runtime: &LogRuntime) {
    if let Some(worker) = runtime.worker.lock().take() {
        if !worker.stop(STOP_TIMEOUT) {
            tracing::warn!("log thread {name} did not stop within {STOP_TIMEOUT:?}");
        }
    }
}
