apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logmaker-data
  namespace: logmaker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logmaker-plugins
  namespace: logmaker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
